// flow-typed signature: e90a36739ad30cb7e75fa3ad079ccd40
// flow-typed version: <<STUB>>/js-md5_v^0.7.1/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-md5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-md5' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-md5/build/md5.min' {
  declare module.exports: any;
}

declare module 'js-md5/doc/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'js-md5/doc/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'js-md5/doc/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'js-md5/src/md5' {
  declare module.exports: any;
}

declare module 'js-md5/tests/node-test' {
  declare module.exports: any;
}

declare module 'js-md5/tests/test' {
  declare module.exports: any;
}

declare module 'js-md5/tests/worker-test' {
  declare module.exports: any;
}

declare module 'js-md5/tests/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-md5/build/md5.min.js' {
  declare module.exports: $Exports<'js-md5/build/md5.min'>;
}
declare module 'js-md5/doc/scripts/linenumber.js' {
  declare module.exports: $Exports<'js-md5/doc/scripts/linenumber'>;
}
declare module 'js-md5/doc/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'js-md5/doc/scripts/prettify/lang-css'>;
}
declare module 'js-md5/doc/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'js-md5/doc/scripts/prettify/prettify'>;
}
declare module 'js-md5/src/md5.js' {
  declare module.exports: $Exports<'js-md5/src/md5'>;
}
declare module 'js-md5/tests/node-test.js' {
  declare module.exports: $Exports<'js-md5/tests/node-test'>;
}
declare module 'js-md5/tests/test.js' {
  declare module.exports: $Exports<'js-md5/tests/test'>;
}
declare module 'js-md5/tests/worker-test.js' {
  declare module.exports: $Exports<'js-md5/tests/worker-test'>;
}
declare module 'js-md5/tests/worker.js' {
  declare module.exports: $Exports<'js-md5/tests/worker'>;
}
