// flow-typed signature: 7a29e38d16f98d8067bef64c032b486a
// flow-typed version: <<STUB>>/react-native-infinite-scroll-view_v^0.4.3/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-infinite-scroll-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-infinite-scroll-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-infinite-scroll-view/DefaultLoadingIndicator' {
  declare module.exports: any;
}

declare module 'react-native-infinite-scroll-view/InfiniteScrollView' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-infinite-scroll-view/DefaultLoadingIndicator.js' {
  declare module.exports: $Exports<'react-native-infinite-scroll-view/DefaultLoadingIndicator'>;
}
declare module 'react-native-infinite-scroll-view/InfiniteScrollView.js' {
  declare module.exports: $Exports<'react-native-infinite-scroll-view/InfiniteScrollView'>;
}
